[package]
name = "rust-yt-dl"
version = "0.1.0"
authors = ["skyline <skyline661@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
rocket_codegen = "0.4.6"
