#[global.template_dir]
#template_dir = "src/templates/"

[development]
address = "localhost"
port = 8000
workers =  8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "9EwQXOdyfVOEH+OKRYFSGdF8CKhirx7xrpbkZodshVw="
limits = { forms = 32768 }
template_dir = "src/templates/"
#自定义前缀
#context_path = "/a"

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "9EwQXOdyfVOEH+OKRYFSGdF8CKhirx7xrpbkZodshVw="
limits = { forms = 32768 }
template_dir = "src/templates/"

[production]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "9EwQXOdyfVOEH+OKRYFSGdF8CKhirx7xrpbkZodshVw="
limits = { forms = 32768 }
template_dir = "src/templates/"