[development]
address = "localhost"
port = 8000
workers =  8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "9EwQXOdyfVOEH+OKRYFSGdF8CKhirx7xrpbkZodshVw="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "9EwQXOdyfVOEH+OKRYFSGdF8CKhirx7xrpbkZodshVw="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "9EwQXOdyfVOEH+OKRYFSGdF8CKhirx7xrpbkZodshVw="
limits = { forms = 32768 }